import { test } from 'node:test'
import assert from 'node:assert/strict'
import { createMemoryStore } from '../src/api/memory-store.js'
import { BUILTIN } from '../src/api/permissions.js'

const setup = () => { const s = createMemoryStore(); s.addUser('u1', { name: 'Dana' }); return s }
const org = (s, slug = 'acme') => s.createOrg({ name: 'Acme', slug, ownerId: 'u1', grants: BUILTIN })
const agent = (s, extra = {}) => s.createAgent({ name: 'Larry', provider: 'Anthropic', type: 'coding agent', ownerUserId: 'u1', ...extra })

test('workspace member sessions: default when omitted, round trip, kept on an upsert that omits it', async () => {
  const s = setup()
  const ws = await s.createWorkspace({ ownerUserId: 'u1', name: 'W', createdBy: 'person:u1' })
  const m1 = await s.putWorkspaceMember({ workspaceId: ws.id, account: 'agent:a1', access: 'edit', addedBy: 'person:u1' })
  assert.equal(m1.sessions, 'invited', 'default when omitted')
  const m2 = await s.putWorkspaceMember({ workspaceId: ws.id, account: 'agent:a1', access: 'edit', addedBy: 'person:u1', sessions: 'all' })
  assert.equal(m2.sessions, 'all')
  const m3 = await s.putWorkspaceMember({ workspaceId: ws.id, account: 'agent:a1', access: 'view', addedBy: 'person:u1' })
  assert.equal(m3.sessions, 'all', 'omitted on an update keeps the old value, not the default')
})

test('agent placement: upsert, read, and listAgentPlacements returns only existing rows', async () => {
  const s = setup()
  const a1 = await agent(s)
  const a2 = await agent(s, { name: 'Moe' })
  const p = await s.putAgentPlacement({ agentId: a1.id, reach: 'workspaces', workspaceIds: ['w1'], sessions: 'all', access: 'edit', scopes: ['src'], updatedBy: 'person:u1' })
  assert.deepEqual(p, { agentId: a1.id, reach: 'workspaces', workspaceIds: ['w1'], sessions: 'all', access: 'edit', scopes: ['src'], updatedBy: 'person:u1', updatedAt: p.updatedAt })
  assert.deepEqual(await s.agentPlacement(a1.id), p)
  assert.equal(await s.agentPlacement(a2.id), null)
  const p2 = await s.putAgentPlacement({ agentId: a1.id, reach: 'all', workspaceIds: [], sessions: 'invited', access: 'view', scopes: [], updatedBy: 'person:u1' })
  assert.equal(p2.reach, 'all', 'upsert replaces')
  assert.deepEqual((await s.listAgentPlacements([a1.id, a2.id, 'nope'])).map((x) => x.agentId), [a1.id])
  await assert.rejects(s.putAgentPlacement({ agentId: 'nope', reach: 'manual', updatedBy: 'person:u1' }), (err) => err.code === '23503')
  await assert.rejects(s.putAgentPlacement({ agentId: a1.id, reach: 'manual', scopes: Array.from({ length: 21 }, (_, i) => `d${i}`), updatedBy: 'person:u1' }), (err) => err.code === '23514')
})

test('workspace agent overrides: put, get, list, delete', async () => {
  const s = setup()
  const ws = await s.createWorkspace({ ownerUserId: 'u1', name: 'W', createdBy: 'person:u1' })
  const a = await agent(s)
  assert.equal(await s.workspaceAgentOverride(ws.id, a.id), null)
  const o = await s.putWorkspaceAgentOverride({ workspaceId: ws.id, agentId: a.id, sessions: 'all', excluded: false })
  assert.deepEqual(o, { workspaceId: ws.id, agentId: a.id, sessions: 'all', excluded: false })
  assert.deepEqual(await s.workspaceAgentOverride(ws.id, a.id), o)
  assert.deepEqual((await s.listWorkspaceAgentOverrides(ws.id)).map((x) => x.agentId), [a.id])
  assert.equal(await s.deleteWorkspaceAgentOverride(ws.id, a.id), true)
  assert.equal(await s.deleteWorkspaceAgentOverride(ws.id, a.id), false)
  assert.equal(await s.workspaceAgentOverride(ws.id, a.id), null)
  await assert.rejects(s.putWorkspaceAgentOverride({ workspaceId: 'nope', agentId: a.id }), (err) => err.code === '23503')
  await assert.rejects(s.putWorkspaceAgentOverride({ workspaceId: ws.id, agentId: 'nope' }), (err) => err.code === '23503')
})

test('session agent exclusions: add, has, list, remove', async () => {
  const s = setup()
  const a = await agent(s)
  await s.ingestPresence([{ id: 'e1', type: 'start', room: 'room-a', account: 'person:u1', owner: true, name: 'Dana', at: 1000 }], 1000)
  assert.equal(await s.sessionAgentExcluded('room-a', a.id), false)
  const row = await s.addSessionAgentExclusion({ room: 'room-a', agentId: a.id, excludedBy: 'person:u1' })
  assert.deepEqual(row, { room: 'room-a', agentId: a.id, excludedBy: 'person:u1', createdAt: row.createdAt })
  assert.equal(await s.sessionAgentExcluded('room-a', a.id), true)
  assert.deepEqual((await s.listSessionAgentExclusions('room-a')).map((x) => x.agentId), [a.id])
  assert.equal(await s.removeSessionAgentExclusion('room-a', a.id), true)
  assert.equal(await s.removeSessionAgentExclusion('room-a', a.id), false)
  assert.equal(await s.sessionAgentExcluded('room-a', a.id), false)
  await assert.rejects(s.addSessionAgentExclusion({ room: 'nope', agentId: a.id, excludedBy: 'person:u1' }), (err) => err.code === '23503')
})

test('agent webhook: put, get, delete; keeps createdAt on an update', async () => {
  const s = setup()
  const a = await agent(s)
  assert.equal(await s.agentWebhook(a.id), null)
  const w = await s.putAgentWebhook({ agentId: a.id, url: 'https://example.com/hook', secret: 's1' })
  assert.deepEqual([w.agentId, w.url, w.secret], [a.id, 'https://example.com/hook', 's1'])
  assert.deepEqual(await s.agentWebhook(a.id), w)
  const w2 = await s.putAgentWebhook({ agentId: a.id, url: 'https://example.com/hook2', secret: 's2' })
  assert.equal(w2.createdAt, w.createdAt, 'keeps createdAt on an update')
  assert.equal(w2.url, 'https://example.com/hook2')
  assert.equal(await s.deleteAgentWebhook(a.id), true)
  assert.equal(await s.deleteAgentWebhook(a.id), false)
  assert.equal(await s.agentWebhook(a.id), null)
})

test('listOrgAgents returns only that org\'s non-revoked agents, by name', async () => {
  const s = setup()
  const o = await org(s)
  const other = await org(s, 'other')
  const zeta = await s.createAgent({ name: 'Zeta', provider: 'Anthropic', type: 'coding agent', orgId: o.id })
  const alpha = await s.createAgent({ name: 'Alpha', provider: 'Anthropic', type: 'coding agent', orgId: o.id })
  const gone = await s.createAgent({ name: 'Gone', provider: 'Anthropic', type: 'coding agent', orgId: o.id })
  await s.createAgent({ name: 'Elsewhere', provider: 'Anthropic', type: 'coding agent', orgId: other.id })
  await s.revokeAgent(gone.id)
  assert.deepEqual((await s.listOrgAgents(o.id)).map((x) => x.id), [alpha.id, zeta.id])
})

test('agent invite carries workspace fields, defaulting to null', async () => {
  const s = setup()
  const o = await org(s)
  const ws = await s.createWorkspace({ orgId: o.id, name: 'W', createdBy: 'person:u1' })
  const i = await s.createAgentInvite({ tokenHash: 'h1', orgId: o.id, createdBy: 'u1', expiresAt: Date.now() + 60000, workspaceId: ws.id, workspaceAccess: 'edit', workspaceSessions: 'all' })
  assert.deepEqual([i.workspaceId, i.workspaceAccess, i.workspaceSessions], [ws.id, 'edit', 'all'])
  assert.deepEqual([(await s.agentInviteById(i.id)).workspaceId, (await s.agentInviteById(i.id)).workspaceAccess], [ws.id, 'edit'])
  const noWs = await s.createAgentInvite({ tokenHash: 'h2', ownerUserId: 'u1', expiresAt: Date.now() + 60000 })
  assert.deepEqual([noWs.workspaceId, noWs.workspaceAccess, noWs.workspaceSessions], [null, null, null])
})

test('deleting an agent drops its placement, overrides, exclusions and webhook', async () => {
  const s = setup()
  const ws = await s.createWorkspace({ ownerUserId: 'u1', name: 'W', createdBy: 'person:u1' })
  const a = await agent(s)
  await s.putAgentPlacement({ agentId: a.id, reach: 'manual', updatedBy: 'person:u1' })
  await s.putWorkspaceAgentOverride({ workspaceId: ws.id, agentId: a.id, excluded: true })
  await s.ingestPresence([{ id: 'e1', type: 'start', room: 'room-a', account: 'person:u1', owner: true, name: 'Dana', at: 1 }], 1)
  await s.addSessionAgentExclusion({ room: 'room-a', agentId: a.id, excludedBy: 'person:u1' })
  await s.putAgentWebhook({ agentId: a.id, url: 'https://example.com/hook', secret: 's' })
  await s.deleteAgent(a.id)
  assert.equal(await s.agentPlacement(a.id), null)
  assert.equal(await s.workspaceAgentOverride(ws.id, a.id), null)
  assert.equal(await s.sessionAgentExcluded('room-a', a.id), false)
  assert.equal(await s.agentWebhook(a.id), null)
})

test('deleting a workspace drops its agent overrides', async () => {
  const s = setup()
  const ws = await s.createWorkspace({ ownerUserId: 'u1', name: 'W', createdBy: 'person:u1' })
  const a = await agent(s)
  await s.putWorkspaceAgentOverride({ workspaceId: ws.id, agentId: a.id, excluded: true })
  await s.deleteWorkspace(ws.id)
  assert.equal(await s.workspaceAgentOverride(ws.id, a.id), null)
})

test('ending a session drops its agent exclusions', async () => {
  const s = setup()
  const o = await org(s)
  const a = await s.createAgent({ name: 'Bot', provider: 'Anthropic', type: 'coding agent', orgId: o.id })
  await s.ingestPresence([{ id: 'e1', type: 'start', room: 'room-a', account: 'person:u1', owner: true, name: 'Dana', at: 1 }], 1)
  await s.addSessionAgentExclusion({ room: 'room-a', agentId: a.id, excludedBy: 'person:u1' })
  assert.equal(await s.sessionAgentExcluded('room-a', a.id), true)
  await s.deleteUser('u1')
  assert.equal(await s.sessionByRoom('room-a'), null)
  assert.equal(await s.sessionAgentExcluded('room-a', a.id), false)
})
