import { test } from 'node:test'
import assert from 'node:assert/strict'
import { createMemoryStore } from '../../src/api/memory-store.js'
import { BUILTIN } from '../../src/api/permissions.js'

const setup = () => { const s = createMemoryStore(); s.addUser('u1', { name: 'Dana' }); s.addUser('u2', { name: 'Eli' }); return s }
const org = (s, slug = 'acme') => s.createOrg({ name: 'Acme', slug, ownerId: 'u1', grants: BUILTIN })
const profile = (name, extra = {}) => ({ name, provider: 'Anthropic', type: 'coding agent', ...extra })

test('agents belong to one person or one org, carry a profile, and a key belongs to one agent', async () => {
  const s = setup()
  const o = await org(s)
  const mine = await s.createAgent(profile('Larry', { description: 'Writes tests', publicKey: 'pk1', ownerUserId: 'u1', invitedBy: 'u1' }))
  assert.deepEqual(
    [mine.name, mine.provider, mine.type, mine.description, mine.ownerUserId, mine.orgId, mine.invitedBy, mine.revokedAt, mine.lastUsedAt],
    ['Larry', 'Anthropic', 'coding agent', 'Writes tests', 'u1', null, 'u1', null, null]
  )
  const theirs = await s.createAgent(profile('Bot', { orgId: o.id, invitedBy: 'u1' }))
  assert.deepEqual([theirs.orgId, theirs.publicKey, theirs.description], [o.id, null, ''])
  await s.createAgent(profile('NoKey', { ownerUserId: 'u2' }))
  await assert.rejects(s.createAgent(profile('Dup', { publicKey: 'pk1', ownerUserId: 'u2' })), (err) => err.code === '23505')
  await assert.rejects(s.createAgent(profile('Both', { ownerUserId: 'u1', orgId: o.id })), (err) => err.code === '23514')
  await assert.rejects(s.createAgent(profile('Neither')), (err) => err.code === '23514')
  assert.equal((await s.agentById(mine.id)).name, 'Larry')
  assert.equal((await s.agentByPublicKey('pk1')).id, mine.id)
  assert.equal(await s.agentByPublicKey('nope'), null)
  assert.equal(await s.agentByPublicKey(null), null)
  assert.deepEqual((await s.listPersonalAgents('u1')).map((a) => a.id), [mine.id], 'org agents are not personal')
})

test('touching and revoking an agent; revoked agents leave the personal list', async () => {
  const s = setup()
  const a = await s.createAgent(profile('Larry', { ownerUserId: 'u1', invitedBy: 'u1' }))
  await s.touchAgent(a.id)
  assert.ok((await s.agentById(a.id)).lastUsedAt > 0)
  assert.equal(await s.revokeAgent(a.id), true)
  assert.equal(await s.revokeAgent(a.id), false, 'once')
  assert.ok((await s.agentById(a.id)).revokedAt > 0)
  assert.deepEqual(await s.listPersonalAgents('u1'), [])
})

test('org agents join as members with no role, named after the agent, in their own org only', async () => {
  const s = setup()
  const o = await org(s); const other = await org(s, 'other')
  const bot = await s.createAgent(profile('Bot', { orgId: o.id, invitedBy: 'u1' }))
  const mine = await s.createAgent(profile('Larry', { ownerUserId: 'u1', invitedBy: 'u1' }))
  const m = await s.addAgentMember({ orgId: o.id, agentId: bot.id, roleId: null })
  assert.deepEqual([m.agentId, m.userId, m.roleId], [bot.id, null, null])
  await assert.rejects(s.addAgentMember({ orgId: other.id, agentId: bot.id }), (err) => err.code === '23503')
  await assert.rejects(s.addAgentMember({ orgId: o.id, agentId: mine.id }), (err) => err.code === '23503', 'a personal agent')
  await assert.rejects(s.addAgentMember({ orgId: o.id, agentId: bot.id }), (err) => err.code === '23505', 'once per org')
  assert.equal((await s.memberByAgent(o.id, bot.id)).id, m.id)
  assert.deepEqual((await s.listMembers(o.id)).map((x) => [x.name, x.provider, x.type]), [['Dana', null, null], ['Bot', 'Anthropic', 'coding agent']])
  const team = await s.createTeam({ orgId: o.id, name: 'Core' })
  await s.addTeamMember({ teamId: team.id, memberId: m.id, access: 'viewer' })
  await s.addTeamMember({ teamId: team.id, memberId: (await s.memberOf(o.id, 'u1')).id, access: 'editor' })
  assert.deepEqual((await s.listTeamMembers(team.id)).map((x) => [x.name, x.kind]), [['Bot', 'agent'], ['Dana', 'person']])
})

test('deleting an agent, its org or its person removes it and its membership', async () => {
  const s = setup()
  const o = await org(s)
  const bot = await s.createAgent(profile('Bot', { orgId: o.id, invitedBy: 'u2' }))
  await s.addAgentMember({ orgId: o.id, agentId: bot.id })
  await s.deleteAgent(bot.id)
  assert.equal(await s.agentById(bot.id), null)
  assert.equal(await s.memberByAgent(o.id, bot.id), null)
  const bot2 = await s.createAgent(profile('Bot', { orgId: o.id, invitedBy: 'u2' }))
  await s.addAgentMember({ orgId: o.id, agentId: bot2.id })
  const larry = await s.createAgent(profile('Larry', { ownerUserId: 'u2', invitedBy: 'u2' }))
  await s.deleteUser('u2')
  assert.equal(await s.agentById(larry.id), null, "a person's own agents go with them")
  assert.equal((await s.agentById(bot2.id)).invitedBy, null, 'org agents stay; the inviter is forgotten')
  await s.deleteOrg(o.id)
  assert.equal(await s.agentById(bot2.id), null)
})

test('agent invites: a person or an org, found by token, used once while open, cancelled once', async () => {
  const s = setup()
  const o = await org(s)
  const role = (await s.listRoles(o.id)).find((r) => r.builtin === 'member')
  const t = Date.now()
  const mine = await s.createAgentInvite({ tokenHash: 'h1', ownerUserId: 'u1', createdBy: 'u1', expiresAt: t + 60_000 })
  assert.deepEqual([mine.usedAt, mine.usedByAgentId, mine.cancelledAt, mine.teams, mine.roleId], [null, null, null, [], null])
  const theirs = await s.createAgentInvite({ tokenHash: 'h2', orgId: o.id, createdBy: 'u1', roleId: role.id, teams: [{ teamId: 't1', access: 'viewer', scopes: ['src'] }], expiresAt: t + 60_000 })
  assert.deepEqual(theirs.teams, [{ teamId: 't1', access: 'viewer', scopes: ['src'] }])
  await assert.rejects(s.createAgentInvite({ tokenHash: 'h3', ownerUserId: 'u1', orgId: o.id, expiresAt: t }), (err) => err.code === '23514')
  await assert.rejects(s.createAgentInvite({ tokenHash: 'h3', ownerUserId: 'u1', roleId: role.id, expiresAt: t }), (err) => err.code === '23514', 'no role without an org')
  const other = await org(s, 'other')
  await assert.rejects(s.createAgentInvite({ tokenHash: 'h3', orgId: other.id, roleId: role.id, expiresAt: t }), (err) => err.code === '23503')
  assert.equal((await s.agentInviteByToken('h1')).id, mine.id)
  assert.equal((await s.agentInviteById(theirs.id)).orgId, o.id)
  assert.equal(await s.agentInviteByToken('nope'), null)
  assert.deepEqual((await s.listAgentInvites({ ownerUserId: 'u1' })).map((i) => i.id), [mine.id])
  assert.deepEqual((await s.listAgentInvites({ orgId: o.id })).map((i) => i.id), [theirs.id])

  assert.equal(await s.claimAgentInvite(mine.id), true)
  assert.equal(await s.claimAgentInvite(mine.id), false, 'once')
  assert.equal(await s.cancelAgentInvite(mine.id), false, 'a used invite is not cancelled')
  await s.releaseAgentInvite(mine.id)
  assert.equal((await s.agentInviteById(mine.id)).usedAt, null, 'a failed join reopens it')
  const bot = await s.createAgent(profile('Bot', { ownerUserId: 'u1' }))
  assert.equal(await s.claimAgentInvite(mine.id), true)
  await s.setInviteAgent(mine.id, bot.id)
  assert.equal((await s.agentInviteById(mine.id)).usedByAgentId, bot.id)

  assert.equal(await s.cancelAgentInvite(theirs.id), true)
  assert.equal(await s.cancelAgentInvite(theirs.id), false)
  assert.equal(await s.claimAgentInvite(theirs.id), false, 'a cancelled invite is never used')
  const old = await s.createAgentInvite({ tokenHash: 'h4', ownerUserId: 'u1', expiresAt: Date.now() - 1 })
  assert.equal(await s.claimAgentInvite(old.id), false, 'an expired invite is never used')
  assert.equal(await s.cancelAgentInvite(old.id), false, 'an expired invite is never cancelled')
})

test("deleting a role clears it from agent invites; deleting the inviter's org or account removes theirs", async () => {
  const s = setup()
  const o = await org(s)
  const lead = await s.createRole({ orgId: o.id, name: 'Lead', grants: {} })
  const i = await s.createAgentInvite({ tokenHash: 'h1', orgId: o.id, createdBy: 'u2', roleId: lead.id, expiresAt: Date.now() + 60_000 })
  await s.deleteRole(lead.id)
  assert.equal((await s.agentInviteById(i.id)).roleId, null)
  const p = await s.createAgentInvite({ tokenHash: 'h2', ownerUserId: 'u2', createdBy: 'u2', expiresAt: Date.now() + 60_000 })
  await s.deleteUser('u2')
  assert.equal(await s.agentInviteById(p.id), null)
  assert.equal((await s.agentInviteById(i.id)).createdBy, null)
  await s.deleteOrg(o.id)
  assert.equal(await s.agentInviteById(i.id), null)
})

test('agent keys: found by either hash; a refresh key is spent once; a family is revoked together', async () => {
  const s = setup()
  const a = await s.createAgent(profile('Larry', { ownerUserId: 'u1', invitedBy: 'u1' }))
  const t = Date.now()
  const pair = (familyId, n) => s.createAgentKeys({ agentId: a.id, familyId, accessHash: `a${n}`, refreshHash: `r${n}`, accessExpiresAt: t + 1000, refreshExpiresAt: t + 2000 })
  const k1 = await pair('f1', 1)
  assert.deepEqual([k1.refreshedAt, k1.revokedAt], [null, null])
  assert.equal((await s.agentKeyByAccess('a1')).id, k1.id)
  assert.equal((await s.agentKeyByRefresh('r1')).id, k1.id)
  assert.equal(await s.claimRefresh(k1.id), true)
  assert.equal(await s.claimRefresh(k1.id), false, 'spent')
  await s.releaseRefresh(k1.id)
  assert.equal((await s.agentKeyByRefresh('r1')).refreshedAt, null, 'released: free to claim again')
  assert.equal(await s.claimRefresh(k1.id), true, 'and claiming it again works')
  const k2 = await pair('f1', 2)
  await pair('f2', 3)
  await s.revokeFamily('f1')
  assert.ok((await s.agentKeyByAccess('a2')).revokedAt > 0)
  assert.equal(await s.claimRefresh(k2.id), false, 'revoked keys are never spent')
  await s.releaseRefresh(k1.id)
  assert.ok((await s.agentKeyByRefresh('r1')).refreshedAt > 0, 'a revoked key is never un-released')
  assert.equal((await s.agentKeyByAccess('a3')).revokedAt, null, 'another family is untouched')
  assert.equal((await s.listAgentKeys(a.id)).length, 3)
  await assert.rejects(s.createAgentKeys({ agentId: 'nope', familyId: 'f', accessHash: 'x', refreshHash: 'y', accessExpiresAt: t, refreshExpiresAt: t }), (err) => err.code === '23503')
  await s.revokeAgent(a.id)
  assert.ok((await s.agentKeyByAccess('a3')).revokedAt > 0, 'revoking the agent revokes every family')
})

test('team members carry folders: set on add, changed with access, and listed per member', async () => {
  const s = setup()
  const o = await org(s)
  const bot = await s.createAgent(profile('Bot', { orgId: o.id, invitedBy: 'u1' }))
  const m = await s.addAgentMember({ orgId: o.id, agentId: bot.id })
  const team = await s.createTeam({ orgId: o.id, name: 'Core' })
  await s.addTeamMember({ teamId: team.id, memberId: m.id, access: 'editor', scopes: ['src', 'docs'] })
  assert.deepEqual(await s.teamsOfMember(m.id), [{ teamId: team.id, access: 'editor', scopes: ['src', 'docs'] }])
  assert.deepEqual((await s.setTeamAccess(team.id, m.id, 'viewer')).scopes, ['src', 'docs'], 'folders stay unless given')
  assert.deepEqual((await s.setTeamAccess(team.id, m.id, 'viewer', ['web'])).scopes, ['web'])
  await assert.rejects(s.setTeamAccess(team.id, m.id, 'viewer', Array.from({ length: 21 }, (_, i) => `d${i}`)), (err) => err.code === '23514')
})
